name: Deploy site to S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
          
      - name: Deploy site
        uses: TobiasCGoetz/hugo-s3-deploy-action@master
        env:
          AWS_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET }}
          # HUGO_DEPLOY_URL: ${{ secrets.HUGO_DEPLOY_URL }} #for AWS "s3://<Bucket Name>?region=<AWS region>"
          MINIFY: 'true'